GET http://localhost:3000/notes/ 

###

GET http://localhost:3000/notes/40 

###

POST http://localhost:3000/notes/add
Content-Type: application/json

{
"text":"hej test"
}

###

PUT http://localhost:3000/notes/edit
Content-Type: application/json

{
    "title":"Glad när saker funkar",
    "text":"Hej jag finns i databasen igen",
    "id":68
}

###

DELETE http://localhost:3001/notes/delete/33

###